### ISSUE TITLE
StringBuilder should be named String_Builder

### ISSUE THREAD

**Issue by WalkerCodeRanger** [adamant/Adamant.Compiler#28]

**Comment by WalkerCodeRanger** [comment]
Likewise for other mutable types in the RuntimeLibrary

**Comment by Raelifin** [comment]
Do FileReader and FileWriter count as "other mutable types". The only non-StringBuilder mutable type I see is ResourceManager.

**Comment by WalkerCodeRanger** [comment]
Yep, FileReader and FileWriter are the other ones besides StringBuilder.

ResourceManager isn't visible to Adamant code because it doesn't have an underscore at the end.  This is intentional.  I'm not sure what the right naming conventions are for those, but am not to worried about it because that will go away.  I wanted to change the others so that Adamant code wouldn't have to be changed later.

**Comment by WalkerCodeRanger** [comment]
Done in a6370023427a69292f5ceba64d0ef7f50313edcc and 3e13243c119d954fd905c590c23f293c9d8206b1
